### ISSUE TITLE
Maian HTTP error

### ISSUE THREAD

**Issue by LorenzoZaccagnini** [smartbugs/smartbugs#110]
During an integration of SmartBugs with Github Actions I have experienced this issue, I guess it's related to Maian. This causes the tests failure.

**GH actions error logs**

` requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/8c34f235473fdc35c97b20002b4aa4c7c21492c37a667a25df40e90b1b4205cb/start`

`docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/8c34f235473fdc35c97b20002b4aa4c7c21492c37a667a25df40e90b1b4205cb/start: Bad Request ("OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/runMAIANall.sh": stat /runMAIANall.sh: no such file or directory: unknown")`

This is how SmartBugs is integrated in the GH actions
```
 - name: Clone SmartBugs Repo
      run: git clone https://github.com/smartbugs/smartbugs.git
    - name: Remove SmartBugs Results and Install SmartBugs Dependencies
      run: cd smartbugs;rm -r results;pip install -r requirements.txt
    - name: Run SmartBugs Analysis
      run: |
        solidityFiles=($(ls -I Migrations.sol contracts))
        DIR=$(pwd);cd smartbugs
        for sol in "${solidityFiles[@]}"
        do
          echo "Analysing $sol..."
          python smartBugs.py --tool all --file $DIR/contracts/$sol
        done
           
    - name: Move SmartBugs Results to Parent Directory
      run: |
        [[ -d results ]] && rm -r results
        cd smartbugs
        mv results ../
    - name: Commit SmartBugs Results
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: action@github.com
        message: 'chore: added smartbugs results'
        add: 'results'
```

**Comment by gsalzer** [comment]
Thanks for reporting the issue. The problem was related to an erroneous Docker image (mixup between images for master branch and bytecode branch) and has been resolved.
