### ISSUE TITLE
Docker: Internal Server Error qspprotocol/securify-usolc i/o timeout

### ISSUE THREAD

**Issue by limcheekin** [smartbugs/smartbugs#115]
I not sure whether the following error is known or only happened to my repo:
```
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=qspprotocol%2Fsecurify-usolc: Internal Server Error ("Get "https://registry-1.docker.io/v2/qspprotocol/securify-usolc/manifests/sha256:d367b17b6f1ad898a16cf5d663bc95eaf2cefa5de8779590d31575493f9de799": dial tcp 52.55.124.246:443: i/o timeout")
```

You can find out more from the Github Action build log:
https://github.com/limcheekin/eth-dapps-nextjs-boiletplate/runs/5403483616?check_suite_focus=true#step:17:37

And the Github Action file:
https://github.com/limcheekin/eth-dapps-nextjs-boiletplate/blob/master/.github/workflows/truffle.yml#L59

Please advise. Thank you.

**Comment by gsalzer** [comment]
Please reopen the issue as soon as you have new information.
