### ISSUE TITLE
"NameError: name 'logs' is not defined" for MacOS

### ISSUE THREAD

**Issue by Hangyul-Son** [smartbugs/smartbugs#119]
![image](https://user-images.githubusercontent.com/47938735/159539392-426056f7-4574-49fe-8b42-cc5526e7fc40.png)

### **The above error is incomprehensible. This error occurs when the project even after...** 
1. freshly cloned from github
2. Installed all the Python requirements3.8.txt
3. Run the 'python3 smartBugs.py --tool oyente --dataset reentrancy' or 'python3 smartBugs.py --tool all --file 
dataset/reentrancy/simple_dao.sol'

**However even after following the steps in order, an exception is rising: 'NameError: name 'logs' is not defined'.**

<img width="696" alt="Screen Shot 2022-03-23 at 1 36 32" src="https://user-images.githubusercontent.com/47938735/159541659-2a8e3cdb-5713-468e-8ce8-e023da78778c.png">

**Docker is downloaded and docker image up active. The computer in utilization is Apple with m1 processor.** 
What  can be the solution to this error?

**Comment by WoutOnGitHub** [comment]
I'm also using an M1 and getting the same problem. I'll try running it on my linux machine in 2 days to see if it is an Apple problem. Might try it earlier if i feel like setting up a VM

**Comment by shawn-skt** [comment]
> This repo has one PR and that guys code fixed it for me on the M1

hello, can you tell us which PR fixed it? Txs

**Comment by WoutOnGitHub** [comment]
This repo has only one PR

**Comment by shawn-skt** [comment]
Txs a lot

**Comment by jff** [comment]
Thanks for opening the issue, @Hangyul-Son.

Using the `master` branch, I was unable to replicate the error on my side (Ubuntu, Python 3.9.7). What version of Python are you using?

**Comment by Hangyul-Son** [comment]
Thanks for the reply, @jff 

Python version I was using is 3.8.7.
I have rechecked error also with Python 3.9.7 on my m1 device, but python version doesn't seem to be the matter.

**Comment by gsalzer** [comment]
> This repo has one PR and that guys code fixed it for me on the M1

Are you referring to PR #44 ? How did you apply it to the master branch, as it is no longer compatible?

I cannot reproduce the problem (same as @jff), and I try to understand what you have changed to make it work. It seems that you invoke smartbugs differently, as `logs` should be defined as soon as the line `logs = open(...)` has been executed. Thanks!

**Comment by gsalzer** [comment]
@WoutOnGitHub What you did when checking out PR#44 was nothing but reverting to an old version of smartbugs (with the patch PR#44 in fact unrelated to the issue). The old smartbugs is not able to handle new Solidity versions.
I think the underlying issue is that it is not safe to distribute file handles (like the one for the log file) between parallel processes. Apparently it worked in the old smartbugs, and it works in the new smartbugs on some architectures, but apparently not on the new MacBook with M1.
Thanks for reporting the problem, I will fix it as soon as possible.

**Comment by VikingKingWout** [comment]
Oh thx for the explanation. I hope you fix it soon.

**Comment by RobinXieNZ** [comment]
I'm getting the same error, and I'm using an old Intel Mac. Seems it's not just for M1.

**Comment by RobinXieNZ** [comment]
I'm getting the same error, and I'm using an old Intel Mac. Seems it's not just for M1.

**Comment by gsalzer** [comment]
I've started a new branch, `macos-fix`, that will eventually become the master branch. Please checkout it out and see whether it works for you. I had temporary access to a mac, and it seems to work.
Thanks in advance for any reports on successes and failures.

**Comment by shawn-skt** [comment]
> I've started a new branch, `macos-fix`, that will eventually become the master branch. Please checkout it out and see whether it works for you. I had temporary access to a mac, and it seems to work. Thanks in advance for any reports on successes and failures.

It works for me on M1. Thanks a lot!

**Comment by WoutOnGitHub** [comment]
> Contributor

It works for me as well. (On my macbook m1)

**Comment by Hangyul-Son** [comment]
It is working now:) Thank a lot!

**Comment by gsalzer** [comment]
@Hangyul-Son @shawn-skt @WoutOnGitHub Thanks for testing! For now, I regard this issue as solved, and close it.
