### ISSUE TITLE
All I get is errors!

### ISSUE THREAD

**Issue by stebansaa** [smartbugs/smartbugs#123]
Could not find any real results on the logs, on each directory, and then the process looks like this:

Arguments passed: ['smartBugs.py', '--tool', 'all', '--file', 'test.sol']
Pulling image qspprotocol/oyente-0.4.25, this may take a while ...
Image qspprotocol/oyente-0.4.25 pulled
Pulling image smartbugs/manticore, this may take a while ...
Image smartbugs/manticore pulled
Pulling image trailofbits/slither, this may take a while ...
Image trailofbits/slither pulled
Pulling image smartbugs/maian:solc5.10, this may take a while ...
Image smartbugs/maian:solc5.10 pulled
Pulling image nveloso/conkas, this may take a while ...
Image nveloso/conkas pulled
Pulling image qspprotocol/mythril-usolc, this may take a while ...
Image qspprotocol/mythril-usolc pulled
Pulling image smartbugs/smartcheck, this may take a while ...
Image smartbugs/smartcheck pulled
Pulling image christoftorres/honeybadger, this may take a while ...
Image christoftorres/honeybadger pulled
Pulling image christoftorres/osiris, this may take a while ...
Image christoftorres/osiris pulled
Pulling image qspprotocol/securify-usolc, this may take a while ...
Image qspprotocol/securify-usolc pulled
Pulling image smartbugs/solhint, this may take a while ...
Image smartbugs/solhint pulled
[1/11] test.sol [slither] in 0:00:13
Solc experienced a fatal error. Check the results file for more info
honeybadger, test.sol
[2/11] test.sol [honeybadger] in 0:00:02
[3/11] test.sol [solhint] in 0:00:02
[4/11] test.sol [maian] in 0:01:01
[5/11] test.sol [smartcheck] in 0:00:05
Error parsing output of securify for file test.sol
"filename 'results/live.json' not found"
[6/11] test.sol [securify] in 0:00:02
[7/11] test.sol [conkas] in 0:00:04
Solc experienced a fatal error. Check the results file for more info
osiris, test.sol
[8/11] test.sol [osiris] in 0:00:02
Solc experienced a fatal error. Check the results file for more info
mythril, test.sol
[9/11] test.sol [mythril] in 0:00:03
Solc experienced a fatal error. Check the results file for more info
oyente, test.sol
[10/11] test.sol [oyente] in 0:00:02
[11/11] test.sol [manticore] in 0:00:17
Analysis completed.
It took 0:21:03 to analyse all files.

**Comment by gsalzer** [comment]
Can you post `test.sol`?

**Comment by gsalzer** [comment]
Without further information there is no chance to help or explain ... closing the issue for now. Feel free to add more hints.
