### ISSUE TITLE
No compiler found for file 'dataset/reentrancy/

### ISSUE THREAD

**Issue by lalaaaaaaa** [smartbugs/smartbugs#125]
I notice that you have updated smartbugs. When I use smartbugs1.1.0. I meet a question as follows. I have no idea how to solve it . Can you please point it out?
![B767870E-BF17-4fcc-B063-B6BD1DA5694D](https://user-images.githubusercontent.com/32992534/169069243-b3f54abf-89e1-4f35-9dcd-9ba7409473b4.png)

**Comment by gsalzer** [comment]
Closing for now, as without further information it doesn't seem possible to clarify the issue.
