### ISSUE TITLE
Problem with the solidity complier

### ISSUE THREAD

**Issue by jinleisun** [smartbugs/smartbugs#14]
An error occurred when I used Osiris for the analysis of the smart contract: 
"ERROR: Solc experienced a fatal error. Check the results file for more info.  "
And the results file show "Solidity compilation failed". The version of the smart contract I analyzed was 0.4.23. My guess is that the solidity compiler caused the error. Can you tell me the reason for the error? Is it Smartbugs or Osiris ? And how can I fix it? 
Hope for your reply , thank you!

**Comment by pedrocrvz** [comment]
Hi @jinleisun, this is definitely an Osiris issue. SmartBugs does not compile solidity, it only checks for the version of the contract to be able to choose the right docker image from the `.yaml` config file, if more than one image is provided ([known limitations](https://github.com/smartbugs/smartbugs#known-limitations)). 
You need to make sure the version of Osiris (docker image) you are using can compile and analyse your contract.
