### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#145]
Currently, SmartBugs requires a Unix-based system and has been known to fail in some Windows systems. It would be desirable to fully support Windows systems.

Some issues will need to be investigated. For example, it seems that the Python Docker API does not work without changes under Windows. At least some elementary calls (like checking whether docker is available) seem to work differently from Linux/Mac.

**Comment by gsalzer** [comment]
@jff Should we close the issue for now? @lmfuerst was able to run Smartbugs under Windows, after debugging issue #140.
