### ISSUE TITLE
Smartbugs fails to detect version when it's defined in less than 3 parts

### ISSUE THREAD

**Issue by yudikubota** [smartbugs/smartbugs#146]
**Describe the bug**
Solidity allows for pragma version to be defined in less than 3 parts like `^0.5`. Smartbugs fails to detect version when this pattern is used and raises a `ValueError: Invalid simple block ''`

Example:
https://etherscan.io/address/0x250aa88c8f54f5e70b94214380342f0d53e42f6c#code

**Platform**

- SmartBugs version: 2.0.0
- Python version: 3.10.6
- OS : Ubuntu
- CPU: AMD

**Comment by gsalzer** [comment]
@yudikubota Please try the most recent version of SmartBugs, either the v2.0.2 release or checkout the most recent commit. I think this bug has been fixed in commit #3c77e28. Thanks ...

**Comment by jff** [comment]
I cannot reproduce this bug with the latest version (2.0.2).

**Comment by yudikubota** [comment]
My bad
I was using the `master` branch.
I see error handling is much better now, thanks.

![image](https://user-images.githubusercontent.com/22172999/213726686-ded8ee88-64c1-4b59-ade3-70ff2a42b1c3.png)
