### ISSUE TITLE
There may be errors in the data set.

### ISSUE THREAD

**Issue by xf97** [smartbugs/smartbugs#15]
For example, in the unchecked_low_level_calls/FibonacciBalance.sol and unchecked_low_level_calls/unchecked_return_value.sol contracts in the data set sb curated, some low-level call statements have used the require-statements to check the return value, but these statements are still marked as "Unchecked Call Return Value".

**Comment by pedrocrvz** [comment]
Hi @xf97, thanks for the input. The second is clearly a typo, will correct right away.
The first, although is not referent to unchecked low level calls, it has to do with the context that a low level call (`DELEGATECALL`) is executed. You can read more about it [here](https://github.com/sigp/solidity-security-blog#4-delegatecall-1). It's missing some context in the contract, will add the called contract to the file.

**Comment by jff** [comment]
Thank you, @xf97!

This was fixed in #16, which was now merged.
