### ISSUE TITLE
Broken links in wiki

### ISSUE THREAD

**Issue by GGmorello** [smartbugs/smartbugs#162]
**Describe the bug**
Broken links in project's wiki, in "[the command line interface](https://github.com/smartbugs/smartbugs/wiki/The-command-line-interface)" page the links to [`site_cfg.yaml`](https://github.com/smartbugs/smartbugs/blob/sb2.0/site_cfg.yaml) and to [tools folder](https://github.com/smartbugs/smartbugs/tree/sb2.0/tools) are broken

**Platform**
Github website

**Comment by gsalzer** [comment]
@GGmorello Thanks for your feedback, I've fixed the links.
