### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by Chuhanting** [smartbugs/smartbugs#164]
Excuse me, why does this problem occur when I run it?
“Docker: checking for image smartbugs/confuzzius:4315fb7 failed.”
“Docker: Cannot connect to service. Is it installed and running?”

**Comment by gsalzer** [comment]
Have you installed and started the docker services, and did you authorize your user to use it? See the first step of the [installation instructions](https://github.com/smartbugs/smartbugs#installation).
If your problem remains, add some more information: Which operating system are you using? Can you interact with docker from the command line? E.g., under Linux and MacOs, the command
```
docker image ls
```
should list the locally available images. This list may be empty, but the command should not give an error. If it does, check your Docker installation.

**Comment by gsalzer** [comment]
Closing for now, waiting for further information.
