### ISSUE TITLE
About the using SmartBugs as a Python module

### ISSUE THREAD

**Issue by bearookie11** [smartbugs/smartbugs#168]
**Is your feature request related to a problem? Please describe.**
I am interested in learning about SmartBugs. I encounter a problem when I use SmartBugs with Python. I am unsure how to proceed to execute the program

**Describe the solution you'd like**
Could you provide more detailed documentation on using SmartBugs as a Python module?Thank you

**Comment by gsalzer** [comment]
@bearookie11 With "using SmartBugs as a Python module", do you really mean that you want to operate SmartBugs from your own Python program? In this case, did you try the sample code given in the documentation, https://github.com/smartbugs/smartbugs/wiki/Using-SmartBugs-as-a-Python-module ? Can you describe how you call Smartbugs and which problem you encounter? One crucial aspect of SmartBugs as a module is that SmartBugs runs parallel processes, which means that any global initializations and any global code is executed several times unless you check for `__name__ = "__main__".

**Comment by gsalzer** [comment]
Closing for now, as essential information is missing.
