### ISSUE TITLE
error when run mythril in docker

### ISSUE THREAD

**Issue by LeviathanGod** [smartbugs/smartbugs#176]
when I try run mythril:0.23.15 in my ubuntu 20.04.5 
My Python version is 3.8.10 and Smartbugs I think the new version now 

I have pulled and pushed smartsbugs/mythril:0.23.15 and ran a test with command
/smartbugs -t mythril -f victim.sol --processes 2 --mem-limit 4g --timeout 600
Welcome to SmartBugs 2.0.8!
Collecting files ...
1 file to analyse
Assembling tasks ...
1 task to execute
Starting task 1/1: mythril-0.23.15 and victim.sol
Analysis of /home/xuan/Desktop/smartbugs/victim.sol with mythril-0.23.15 failed.
Problem running Docker container: 400 Client Error for http+docker://localhost/v1.41/containers/cbd80a6cdedb6a4e84689fb868fe7269b7f3f4f83783c5b5f427ae6561167f9f/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/sb/bin/do_solidity.sh": stat /sb/bin/do_solidity.sh: no such file or directory: unknown"))
1/1 completed, ETC 0:00:00
Analysis completed in 0:10:37.

![image](https://github.com/smartbugs/smartbugs/assets/106419343/61ba68ca-b4f5-4070-9fcb-cf9d23ce13bd)

**Comment by gsalzer** [comment]
From the command line, as the user you that you use also for smartbugs, try the command
```console
docker run smartbugs/mythril:0.23.15
```
It should display the help text of mythril. If it gives a docker error, your user is probably not allowed to access docker (see the first point of the installation instructions in the main readme), or docker is not properly installed.

**Comment by gsalzer** [comment]
Without further information, I can't analyze the problem. Closing for now.
