### ISSUE TITLE
`smartbugs.json` not written if parsing of results fails

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#179]
**Describe the bug**
When output parsing fails (option `--json` and `--sarif`), smartbugs does not write status information to `smartbugs.json`, so after fixing the parser the analysis has to be repeated instead of just reparsing it. Instead, Smartbugs should behave as if no output option had been specified.

**Platform**

- SmartBugs version: 2.0.8

**Comment by MarkLee131** [comment]
also encountered this issue. Hope it will be fixed soon :)

**Comment by gsalzer** [comment]
@MarkLee131 fixed
