### ISSUE TITLE
chmod: cannot access '/sb/bin/solc': No such file or directory

### ISSUE THREAD

**Issue by 1664566760** [smartbugs/smartbugs#191]
**Describe the bug**
I am running a command “./ Smartbugs - t honeybadger - f/mnt/c/Users/16645/Desktop/ZKP/test/datasets_mini test/0x909E3-486e1f85. sol -- processes 4-- mem limit 4g -- timeout 600 "After running, the result shows no problem, but the output result of the file shows that solc compilation failed “chmod: cannot access '/sb/bin/solc': No such file or directory”

![image](https://github.com/user-attachments/assets/d1bb2077-677e-4250-8719-2cfe8a9a4de1)
![image](https://github.com/user-attachments/assets/91219ec5-f5eb-4c1c-b0cc-13290f34cf62)

- SmartBugs version: [e.g. 2.0.2]
- Python version: [e.g. 3.10.6]
- OS : [wsl, Ubuntu22..04,]
- CPU: [32]
 
**Additional context**

**Comment by gsalzer** [comment]
It seems you are using a modified version of SmartBugs, not the one from this repository. When collecting the tasks and checking for the required solc-versions, your output shows the lines
```console
Switching to solc version 0.8.0 using solc-select...
Switched global version to 0.8.0
```
SmartBugs does not use `solc-select`, but a modified copy of `solcx`, and definitely does not output the lines above.

Either try a clean install from this repository, or report the issue to the SmartBugs fork that you are actually using.
