### ISSUE TITLE
question on statistics

### ISSUE THREAD

**Issue by SunBeomSo** [smartbugs/smartbugs#27]
Hi, I have three questions on statistics. I would be grateful if you could explain if I am misunderstanding something.

**[Q1]** The Table 7 in paper "Empirical Review of Automated Analysis Tools on 47,587
Ethereum Smart Contracts" states that Oyente identified 308 contracts that potentially have reentrancy vulnerabilities.

However, according to the [contracts.csv](https://github.com/smartbugs/smartbugs-results/blob/master/metadata/contracts.csv), the sum of the column ``oyente_reentrancy`` is 260, not 308.

**[Q2]** In Section 3.2 of the ICSE '20 paper, the paper states that

_It is followed by the Reentrancy category with 133 contracts receiving a consensus of four tools or more._

However, according to the column ``reentrancy`` in [contracts.csv](https://github.com/smartbugs/smartbugs-results/blob/master/metadata/contracts.csv), it seems that the number of contracts receiving a consensus of four tools or more is 369, not 133.

**[Q3]** According to the Table 7 in the ICSE '20 paper, Maian identified 44 contracts with access control vulnerabilities.

However, having inspected the [directory](https://github.com/smartbugs/smartbugs-results/tree/master/results/maian/icse20), it seems that Maian identified 45 contracts with access control vulnerabilities (i.e., prodigal and suicidal), not 44. The lists are:
```
0x1c98eea5fe5e15d77feeabc0dfcfad32314fd481
0x7bd9084fdd5d021c226918d86c0721cb088b9b4a
0x3bcaf56923335062e8f272d011efd2e40fa42147
0x9db3fd94a5bb1acdaef28ae483fe6b0d49746678
0x371f24324e223a5ca99f26c4993aae53149b2597
0xb34aa41593deabb2b17e7507e3e413c58f6e0c71
0x05f8b281410c9327a1bbf508db380fd967c31df6
0x17e5f19d430788323863c6798ecd762a40de29f5
0xd152f549545093347a162dce210e7293f1452150
0xead71f4d060ddc7656c959b482fbdfaca95c5d9d
0xf34839b310097fcb4cf3a302dda8cc9b57501083
0xf3dce610acbfbcbb4efc12c4c2e3be063128baad
0xa21c9a3ae47103b1fd1dfa04766c4d00c19e1ff6
0xeefdfa0f6a921044e7901d18e6794c0a7baff4d7
0xe923dd860176d3ef69d7852257cc773900807f7c
0x39730ebfeb4e0c9c2e2645c528c00ee7b98ecfb2
0x612f1bdbe93523b7f5036efa87493b76341726e3
0xdd97853ba34af302f3d6a6415a750ae38e26d1fc
0x781fb4f25d07de3f3cfe2476645e52e0c661eefc
0xf55a32f0107523c14027c4a1e6177cd7291395a0
0x310b15ad0a8b282ee8011d91c79feba80cb179c8
0xb5630e5dfd604b3b88965f2a5103bbf5e31a7340
0xa7ca36f7273d4d38fc2aec5a454c497f86728a7a
0xd58132f2fbd65f02beee0626542e6ee059009ab4
0xb5c0e43a6330b9eb904ec57ea24d70269ae4652e
WalletLibrary
0x5aef06ec39e98c05201ee1e54b653c372ecb9cf3
0x50430b6201c9859c91a5590ac71700cc71499a0e
0x3da034753b42bda1bcfa682f29685e2fd6729016
0x13a517751318cce71a524006b16f7930b3515ccf
0x43f208d94a82cc2749a140b5e82636f31ce0390d
0xa5fccc3f1a4e56fda5a86f0fe8b7558881b67523
0x9f4fd6c336388f2ab7dc7bbe4740ae7b88b880d7
0x94603d4a41856bccb75cc3603af19fc161a7b6b6
0x8e9f6181371013194d48bc031adf7fe179fb37e3
0xb60e133dacf00b6f560909dc0a5311ae7f9a659b
0x0f7524d64ceb92dae1d1a56b20b6d520134795d4
0x07419940b9a2d1eb54e123bd4853240ffac77186
0x724e3a236d3e9c8ad2c3d1aff181118e6e9b3026
0xd7290307c040f4089f8650b7f7aac3cfe39cd6bd
0x43efc486d1c7c5cb0193e409a73aa33786f5197c
0xe30a76ec9168639f09061e602924ae601d341066
0xc825aa83f12e4d225ea1f21511a68e7aa78a002f
0xfc79774fb9dedeea2325d0d5570554eddc4e6747
0x8960eb9d4a2d153fd7b175c0f3eef8026eb95dfc
```

Could you check this information?

**Comment by jff** [comment]
Thanks for your questions @SunBeomSo. The files to look at are [results_wild.json](https://github.com/smartbugs/smartbugs-results/blob/master/metadata/results_wild.json), which is produced by the script [generate_results_wild.py](https://github.com/smartbugs/smartbugs-results/blob/master/script/generate_results_wild.py).

If you run the script, you'll get the same data as presented in the ICSE paper. Let me know if you have any additional questions or if you find any problems with any of our scripts.

Am I right in assuming that you are part of the team developing VeriSmart? Is there any chance you could integrate it with SmartBugs? :)

**Comment by SunBeomSo** [comment]
@jff Thanks for the answer.

I would try to integrate VeriSmart with SmartBugs.

I have one more question.
For maian, there exists a log for the contract ``WalletLibrary``:
https://github.com/smartbugs/smartbugs-results/tree/master/results/maian/icse20/WalletLibrary

But there are no results on ``WalletLibrary`` contract for other tools. For example, the link below (manticore) does not exist:
https://github.com/smartbugs/smartbugs-results/tree/master/results/manticore/icse20/WalletLibrary

Is ``WalletLibrary`` contract included in SB wild dataset or nor?

**Comment by jff** [comment]
Hi @SunBeomSo, during the execution of our experiments, Manticore was the only tool that faced timeouts. As a result, there might be some result files missing.

By the way, I think it would be better to pose questions like this in the smartbugs-results repository.

Regarding VeriSmart, I am looking forward to seeing it as part of the default distribution. Please let me know if you need any assistance!
