### ISSUE TITLE
Vulnerability that is not a vulnerability

### ISSUE THREAD

**Issue by nveloso** [smartbugs/smartbugs#29]
Hi! I think that in the file insecure_transfer.sol that is part of the arithmetic dataset, the vulnerability at line 17 is not a vulnerability because of the check (require) at line 15. Could you check it?

**Comment by pedrocrvz** [comment]
Hi. Yes, it's wrongly marked as a vuln, only the second ones qualifies as an overflow. 
Can you make the PR for the fix?

**Comment by nveloso** [comment]
Sure!
Also, in contract timelock.sol, line 16 and 17 it is possible an overflow but the probability to occur is low. It should also be annotated as vuln?
In token.sol line 23 it is possible to occur an overflow, it should be annotated as vuln too?
