### ISSUE TITLE
Ground truth of the existence of vulnerabilities

### ISSUE THREAD

**Issue by yxliang01** [smartbugs/smartbugs#31]
While I think there is no ground truth available for SB Wild dataset, I am wondering whether the indicated vulnerabilities in the deployed contracts in SB curated dataset are verified? That is, the contract is indeed vulnerable and the vulnerable statement line number is accurate.

**Comment by jff** [comment]
Hi @yxliang01, thanks for your interest. Yes, SB Curated is mannualy annotated. Obviously, there might be some human error (for example, [this pull request](https://github.com/smartbugs/smartbugs/pull/30) fixes a problem and some typos found recently.
