### ISSUE TITLE
smartbugs/maian docker image

### ISSUE THREAD

**Issue by SunBeomSo** [smartbugs/smartbugs#32]
Hi,

I am using docker image of Maian, provided in https://hub.docker.com/r/smartbugs/maian .

When running smartbugs/maian docker image in parallel with more than 10 processes, I obtained a following error message: 
```
^[[1m[ ] Connecting to PRIVATE blockchain emptychain  ^[[0m.Traceback (most recent call last):
  File "maian.py", line 182, in <module>
    main(sys.argv[1:])
  File "maian.py", line 116, in main
    execute_transactions([{'from':'0x'+MyGlobals.sendingether_account,'to':supposed_contract_address,'value':MyGlobals.send_initial_wei}])
  File "/MAIAN/tool/blockchain.py", line 95, in execute_transactions
    MyGlobals.web3.personal.unlockAccount(tx['from'],'1',15000)
  File "/usr/local/lib/python2.7/dist-packages/web3/personal.py", line 93, in unlockAccount
    [account, passphrase, duration],
  File "/usr/local/lib/python2.7/dist-packages/web3/manager.py", line 93, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python2.7/dist-packages/web3/manager.py", line 76, in _make_request
    return request_func(method, params)
  File "/usr/local/lib/python2.7/dist-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python2.7/dist-packages/web3/middleware/formatting.py", line 25, in middleware
    response = make_request(method, params)
  File "/usr/local/lib/python2.7/dist-packages/web3/providers/rpc.py", line 52, in make_request
    **self.get_request_kwargs()
  File "/usr/local/lib/python2.7/dist-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8550): Read timed out. (read timeout=10)
^[[92m ESTABLISHED ^[[0m
^[[1m[ ] Sending Ether to contract 0x9e536236abf2288a7864c6a1afaa4cb98d464306  ^[[0m
```

When running smartbugs/maian with 2 processes in parallel, I did not encounter the above error messages. Is it a known issue? Is it possible to run smartbugs/maian with more number of processes?

I found that the sentence "Maian uses up to 16GB of RAM" in the ICSE 2020 paper. However, it seems that the above error message is not related to memory issues.

**Comment by jff** [comment]
Hi @SunBeomSo, I currently have no way of reproducing the bug. What is the smaller number of processes for which you get that error? 

I am tagging @tdurieux because he might have some idea of why this happens.

**Comment by tdurieux** [comment]
What is the configuration of your computer?
If I correctly recall Maian consumes a lot of resources. I did not identify a workaround to reduce this problem.

**Comment by SunBeomSo** [comment]
Thanks for the responses.

@jff 
> What is the smaller number of processes for which you get that error?

When running Maian with 4 threads in parallel, it seems to work fine. However, when running it with 6 and 8 threads in parallel respectively, the same problem happened.

As the number of threads running in parallel decreases, frequency of problem occurrence seems to decrease.


@tdurieux 
> What is the configuration of your computer?

I am working on Ubuntu 18.04 with 188GB of memory. When I ran Maian with 8 processes in parallel on my machine, Maian consumed memory less than 10GB and the total CPU usage was also less than 20% (32 threads are available in my machine).

> I did not identify a workaround to reduce this problem.

Haven't you seen the error above before? I wonder whether this problem has not been seen before.

Based on the log above, the problem seems to be related to port issues. I wonder, regarding the experiments for ICSE 2020 paper, whether you have modified port numbers in source code of Maian when running it in parallel for each docker image (or docker container) or whether you simply used smartbugs/maian docker image available in https://hub.docker.com/r/smartbugs/maian.

**Comment by tdurieux** [comment]
For Maian we reduce the number of parallel executions. I don't exactly remember the number of parallel executions.
We did not modify anything else but it took a really long time.

**Comment by SunBeomSo** [comment]
Thanks for the answer.  I do not close this issue since I think there may be someone that encounters this issue, but I think you can close this issue if you want.
