### ISSUE TITLE
skip-existing

### ISSUE THREAD

**Issue by ragarwa2** [smartbugs/smartbugs#33]
Currently the results folder is timestamped to current time
```
output_folder = strftime("%Y%d%m_%H%M", localtime())
```

while for the skip-existing result_folder is this timestamped (current folder) which has no results.. Thus, the entire checking of contracts happen again..

```
for file in files_to_analyze:
   for tool in args.tool:
       results_folder = 'results/' + tool + '/' + output_folder
       if not os.path.exists(results_folder):
            os.makedirs(results_folder)

       if args.skip_existing:
           file_name = os.path.splitext(os.path.basename(file))[0]
           folder = os.path.join(results_folder, file_name, 'result.json')
           if os.path.exists(folder):
               continue
       tasks.append((tool, file))
```

**Comment by jff** [comment]
Thanks for reporting this, @ragarwa2 

One solution to this is to use a fixed output folder and provide an extra option that enables timestamped result folders. What do you think? (cc'ing @pedrocrvz)

**Comment by ragarwa2** [comment]
If this is what you mean:
- adding an extra option for giving, as input, the old results folder dateTime value (in the format "%Y%d%m_%H%M").
I would also suggest to make it an array so that multiple dateTime can be provided towards old result folders.

**Comment by pedrocrvz** [comment]
> Thanks for reporting this, @ragarwa2
> 
> One solution to this is to use a fixed output folder and provide an extra option that enables timestamped result folders. What do you think? (cc'ing @pedrocrvz)

Sure, that's one possibility. We could also iterate over the directories in `/results/[tool]` to check if a directory with the name of the file exists. (the output result of an analysed file is a directory with the file name containing the `result.json` and `result.log` in the timestamped folder)

It should be something like:

```
def file_exists(tool, folder, file_name):
    for root, dirs, files in os.walk('results/' + tool):
        for dirName in dirs:
            if dirName == file_name:
                return True

    return False
```

```
(...)
    for file in files_to_analyze:
        for tool in args.tool:
            results_folder = 'results/' + tool + '/' + output_folder

            if args.skip_existing:
                file_name = os.path.splitext(os.path.basename(file))[0]
                folder = os.path.join(results_folder, file_name, 'result.json')

                if file_exists(tool, folder, file_name):
                    print('Skipping file %s' % file_name)
                    logs.write('Skipping file %s' % file_name)
                    continue
            
            if not os.path.exists(results_folder):
                os.makedirs(results_folder)

            tasks.append((tool, file))
```
