### ISSUE TITLE
Bytecode support: add tool Easyflow

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#56]
https://github.com/Jianbo-Gao/EasyFlow

**Comment by gsalzer** [comment]
A fixed input won't do. Typically, the first four bytes determine the function to be executed in the contract, and the rest should match the types of the required arguments. If we fix the input, then most contracts will end up in the fallback function (if it exists) or will revert (if it doesn't). I have scripts to extract the function signatures from the bytecode, so we could generate transactions for each of them. So some kind of directed fuzzing. But in some sense this would develop a new tool based on Easyflow, and it is unclear in which way this affects the performance of the tool.

I suggest to remove the tool from our list, as it doesn't fit the scheme "only runtime code".

**Comment by jff** [comment]
I agree, I think we can close this issue.
