### ISSUE TITLE
Bytecode support: add tool EthBMC

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#58]
https://github.com/RUB-SysSec/EthBMC

**Comment by tdurieux** [comment]
I added the support for it but the tool is extremely slow. for the contract that I tested the tool did not finish in 30min.
Could be related to the config: https://github.com/smartbugs/smartbugs/blob/bytecode/utils/docker/smartbugs-EthBMC/scripts/run.sh#L8
