### ISSUE TITLE
Bytecode support: add tool Madmax

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#61]
https://github.com/nevillegrech/MadMax

**Comment by gsalzer** [comment]
As far as I can see, Madmax now works (almost). In commit 91ebcaf7d95c105c22338902a6fd14c00276cf75 I modified `Dockerfile` such that also `madmax.dl` gets precompiled, which speeds up the runs. Moreover, I delete `results.json` and `.temp` to avoid that in case of an error, these remnants of the pre-compile are returned as result of the failed run.

There is one bug still: Madmax generates `results.json`, but `result.tar` in the result directory is empty. Is there something like
```console
mv results.json /results
```
missing in `utils/docker/smartbugs-MadMax/scripts/run.sh`?

**Comment by gsalzer** [comment]
Has been fixed with recent updates of the bytecode branch and the images
