### ISSUE TITLE
Bytecode support: extend support for tool Maian

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#64]

**Comment by jff** [comment]
This is ready to test in the bytecode branch. It is taking too long in my laptop... @tdurieux could tou give it a go, please?

**Comment by tdurieux** [comment]
It started the exec on the 500, it is indeed extremely slow and it has a low CPU usage.

**Comment by jff** [comment]
I updated the images and they should work now. @tdurieux Can you please check?

**Comment by tdurieux** [comment]
It seems that the new version is working nicely.

**Comment by jff** [comment]
That's great, @tdurieux 

I noticed that in some executions, it is producing exceptions such as `Exception: 'float' object cannot be interpreted as an integer`

It seems to happen mostly with the PRODIGAL and GREEDY analyses.

Should we take this into consideration for the definition of ìs_sucess`?

**Comment by jff** [comment]
Important note: when analyzing bytecode, maian will not try to confirm the vulnerability! (see lines 149--165 of maian.py).

**Comment by jff** [comment]
Also, the exceptions mentioned above appear even when vulnerabilities are found. Therefore, I am not taking them into consideration in the definition of `is_success`
