### ISSUE TITLE
Start smartbugs log only when starting to work

### ISSUE THREAD

**Issue by gsalzer** [smartbugs/smartbugs#71]
Every run of smartbugs produces a log file in `results/log`.

Currently, literally *every* run produces such a file, even when just displaying the help of smartbugs or when smartbugs immediately aborts because of errors on the command line (which leads to an empty log file).

Suggestion: Start logging only when actually running tools, such that the log files correlate with results in some tool directory.

**Comment by tdurieux** [comment]
It has been fixed in the bytecode branch
