### ISSUE TITLE
Dockerhub will remove images that are not downloaded once per month

### ISSUE THREAD

**Issue by jff** [smartbugs/smartbugs#88]
Perhaps we can create a GitHub Action?

**Comment by gsalzer** [comment]
Why do we have to use Dockerhub? `docker load` allows to load an image from a local tar archive. So we could put the docker images in a companion repository, and smartbugs could `git pull` the most recent image and `docker load` it.

[ Disclaimer: I'm a newbie regarding docker ]

**Comment by gsalzer** [comment]
@tdurieux Do you have a reference to the current policies of `docker.com`? I only found an old announcement that they postpone the expiry to a newer date in 2021, but nothing recent. What are the current conditions regarding the expiry of Docker images on `hub.docker.com`?

**Comment by tdurieux** [comment]
I received this email in January

> Hello,
> 
> As a reminder you’re receiving this email because on August 31, 2021 we updated the [terms](https://email.notify.docker.com/c/eJyFj8tqxDAMRb_G2Tn4NU42XhTK_EZxbSURje3gx2T693XaLrorCARH90q63txAwzKgEUwIxoXm-qbZNPp5WZSbtJ1mqZ3lRLGYKi6fo0_uA_LoUhg2I6dJdrmVIIArL5zkXCs1S5jnhSk97Gar9ShEvhBx73We558NHeyw2r33H0hLey8u41ExRVogP9ABtWsGCBArkfdWw5uz4bC4RiJfr7cp41QomiFg9H3Hmm03HZAxeSL05QjgsYWuh2Bx_4Ulteygw4utLQ7Z-JYR2rNuKdjSM2-pXsPvtNX8d-wLPDptag) applicable to the Docker products or services you use.
> 
> On January 31, 2022, the grace period ends for free commercial use of Docker Desktop in larger enterprises. Companies with more than 250 employees OR more than $10 million USD in annual revenue now require a paid subscription to use Docker Desktop. [Read the blog](https://email.notify.docker.com/c/eJyFkM9uwyAMxp8muTkikJLukEOlqa8xUTABteCIP8v69iPbDr1NsmTp58_-bJvlhBJt7xfOOGcjl6M8STYP5mztpGep5rOQWo3dxCIVb5-DIX3HNGgKvVuE4ThNXNgRGZdWCa2afkLJOc7sTfePxZWy5U5cOn5tse_7y4QGbg9aWyoOYU1KI2yYPBmwlOCAv2LI9ZZ18lvxFCFj-vRNqtaEGDAWwGgyZGo1hwkz7E4VeFKFiGigENwj7ccG4lpL-NAqbMqvsRPvx93ARuATJAw-mmb2ukjH5dER0Pgamh6D8o8_mKkmjQ0ebK2xT4upyWP9Ko6Cyu1pjspR_HlXWf4z-wax4oXD) or visit our [FAQ](https://email.notify.docker.com/c/eJyFjz1uxCAQhU-DOywYbOwUFCtFe40Iw2CjLOBgkLO3XxylSBdpiqdvft48q0aU6DqvgAEwDpLLUbKpt7Nzg5mknmYhjeZkYDEV7569TeYTc29S6DaFCIuBUc4jWs0Gtkz8zUg7aw4WnFi6h9pK2Q8ibgTurc7z_HOhgT174-PalNNfRNxrCR9Gh137NRLxfr1FGacw0IzBR4uZrlkbpDtmnywBeW0EtL6GNo9B-8cvPFLNBhu82Fpjl5Wt2WP9LlsK-miZtlSu5k-aov4zewFnX2IA) to learn more about these updates.
> 
> What you need to know:
> 
> [Docker Desktop](https://email.notify.docker.com/c/eJyFj01uxCAMhU9DdomAEKALFiNVc42KYpOgGULEj9LevqTtortKXlifn_38wCwo0Q_BcMo5ZVwyuUiqJtDeC6ekVXqWzjIi6J5q8J8TJPfAPLkUh81Y0IviC39nSmmJ4kVRRpGCnr1TgsLwNFutRyHzjfB7r_M8_1zo4MgJmqultz98BCyPmg4y31uNb87Gw4Z1J_Pr9eJI2cjFmDGGHbp4zdbheGAOCQiX10ZECC12PUYbnr-wpJYddnixte1DNtBywPZRtxRt6fm2VK_hd7Jq_jP7AtIpZhA) remains free for personal use, education, non-commercial open source projects, and small businesses with fewer than 250 employees AND less than $10 million USD in annual revenue.
> By continuing to use Docker, you are agreeing to the new [Docker Subscription Service Agreement](https://email.notify.docker.com/c/eJyFj8tqxDAMRb_G2Tn4NU42XhTK_EZxbSURje3gx2T693XaLrorCARH90q63txAwzKgEUwIxoXm-qbZNPp5WZSbtJ1mqZ3lRLGYKi6fo0_uA_LoUhg2I6dJdrmVIIArL5zkXCs1S5jnhSk97Gar9ShEvhBx73We558NHeyw2r33H0hLey8u41ExRVogP9ABtWsGCBArkfdWw5uz4bC4RiJfr7cp41QomiFg9H3Hmm03HZAxeSL05QjgsYWuh2Bx_4Ulteygw4utLQ7Z-JYR2rNuKdjSM2-pXsPvtNX8d-wLPDptag).
> For organizations requiring Single Sign-On (SSO), it is now generally available for [Docker Business](https://email.notify.docker.com/c/eJyFj8tuhDAMRb8GdqC8CMwii5Gq-Y0qOA5EnSQoDzHz9w1VF91V8sI6vtf2NWpCibZ3ihHGCGWSykmSeTSLtQJmqeeFS9C0EyTE4ux7NBG-MI0Qfb-rG18Jt3w1Yl0E0ObH24ICJ1gthWnqn2ov5cgdv3fs0eo8zz8bGjhSNBVKbu1aswuYm_hRi_8E7Q_tttDxj-u5gdCBiSGhd8FgGrakAYcDk4umY_JyeDSu-qZHr93zF-ZYE2CDF9tq6JMyNTmsr7JHr3NLtsdyDX8yFfXfsW8EzWSX) subscribers.
> To purchase a Docker subscription, visit our [pricing page](https://email.notify.docker.com/c/eJyFj81uxCAMhJ-G3BLxE2Bz4LBSta9REWMS1AUiAsru2zepeuitkk-fx54ZZyQq9F0wnHJOGVdMSUX14G7ej6CV1TehwDIy0pRr8O_BZfjCMkCO3WrkKOysFGXT7GaFetIMuMQJpB-dANk9zVrrthNxJ_xxznEcfz6cYCsBQlqIeLQaP8HGzYYlEfFxBeop6_nYF4whOSz9Uixgv2EJ2RGurouILrR46jHa8PyFe24F8IQXW1rqinGtBGyvuuZo97PNmuu1_OlRzX9m3_83X94) to compare subscription tiers, starting at just $5 per month, per user on an annual basis. For organizations with more than 50 users requiring an invoice, [contact sales](https://email.notify.docker.com/c/eJyFj8FuhSAQRb9GdxhARV2waNK832imw6CkAgYh9v39w6aL7prMYnJm7ty5Ro-kyLZOSy4lF1IJNSo-dWa2dsBJwTT3CkE0Aw8xO_vsTMQvSh1G3256sGiGRVhaaJxN1eOs5lHyTy7F0gO0u95yPs6mf2vko9Z1XX8uVHAkhy6stcMYMmBmJ-xUBY-S_QeCP8Ctoenf7wcZF0wOLJF3wVBiawIkdlBy0TRS3QpPxhVf98mD23_hGUtCqvBmawlt0qYkR-U7b9HDWdNtMd_Dn1xZ_2f2AjArZXI).

**Comment by gsalzer** [comment]
For none of the subscription schemes on https://www.docker.com/pricing, I found an expiration period for the images. And for educational as well as non-commercial open-source use, Docker is still free. Likewise, the linked blog entry does not mention anything about deletion of images.

**Comment by tdurieux** [comment]
Good news. You can close this issue :)
